a 1:
  url: http://www.amazon.it/s/?field-keywords={%query}
  title: Amazon.it
  tags:
  - affiliate
  - amazon
  - books
  - shopping
  examples:
  - arguments: shakespeare
    description: Search for "shakespeare"
e 0:
  url: https://www.ebay.it/?mkcid=1&mkrid=724-53478-19255-0&siteid=101&campid=5337375636&customid=&toolid=10001&mkevt=1
  title: Ebay.it
  tags:
  - affiliate
  - ebay
  - shopping
e 1:
  url: https://www.ebay.it/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313&_nkw={%query}&_sacat=0&mkcid=1&mkrid=724-53478-19255-0&siteid=101&campid=5337375636&customid=&toolid=10001&mkevt=1
  title: Ebay.it
  tags:
  - affiliate
  - ebay
  - shopping
  examples:
  - arguments: smartphone
    description: Search for "smartphone"
zal 1:
  url: http://www.zalando.it/catalogo/?q={%prodotto}
  title: Zalando.it
  tags:
  - shopping
  - zalando
  examples:
  - arguments: 'calzature '
    description: cercare calzature
