e 0:
  url: http://www.ebay.com.my/
  title: Ebay.com.my
  tags:
  - ebay
  - shopping
e 1:
  url: http://www.ebay.com.my/sch/i.html?_nkw={%query}
  title: Ebay.com.my
  tags:
  - ebay
  - shopping
  examples:
  - arguments: smartphone
    description: Search for "smartphone"
